export const INPUT_SEARCH = 'INPUT_SEARCH';
export const POKEMON_LOAD = 'POKEMON_LOAD';
export const INFO_POKEMON_LOAD = 'INFO_POKEMON_LOAD';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const ADD_SEARCH_POKEMON = 'ADD_SEARCH_POKEMON';

